name: 04-using-actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    # 0. Checkout the code from the repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.0
      - name: Printing folders
        run: ls
    # 1. Install the deps of react application
    # 2. Execute automated tests